In [10]:
from ast import literal_eval

old_x_tuples = [literal_eval(row) for row in df1.old_x]

In [13]:
old_x_tuples_lb = [x[0] for x in old_x_tuples]

In [14]:
old_x_tuples_lb

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 1957,
 0,
 0,
 1969,
 0,
 2343,
 0,
 0,
 0,
 1988,
 1968,
 0,
 0,
 0,
 0,
 0,
 2153,
 0,
 2109,
 2002,
 0,
 0,
 2077,
 2065,
 2058,
 2138,
 0,
 0,
 0,
 0,
 0,
 2143,
 0,
 2230,
 0,
 2321,
 1978,
 0,
 0,
 0,
 2095,
 0,
 2005,
 0,
 0,
 2769,
 2333,
 0,
 0,
 0,
 2339,
 0,
 0,
 0,
 0,
 1989,
 0,
 2381,
 2028,
 1940,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2076,
 2419,
 0,
 0,
 0,
 0,
 0,
 1961,
 2065,
 0,
 2040,
 2152,
 0,
 0,
 2103,
 2164,
 0,
 0,
 1924,
 0,
 2011,
 0,
 1946,
 0,
 2061,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2073,
 0,
 0,
 1962,
 0,
 0,
 0,
 2011,
 2072,
 0,
 0,
 0,
 1988,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2600,
 0,
 0,
 0,
 2168,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1963,
 2440,
 1956,
 0,
 0,
 0,
 2089,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1978,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2015,
 0,
 1953,
 1986,
 1990,
 2084,
 2040,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1960,
 0,
 0,
 2199,
 0,
 0,
 0,
 0,
 0,
 2094,
 0,
 0,
 0,
 2174,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2153,
 2121,
 0,
 1976,
 0,
 1993,
 0,
 0,
 2153,
 0,
 0,
 0,
 2120,
 0,
 0,
 0,
 0,
 0,
 0,
 2001,
 0,
 1924,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1937,
 2049,
 0,
 0,
 0,
 2024,
 0,
 0,
 2002,
 0,
 0,
 2120,
 0,
 0,
 0,
 1963,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1934,
 2050,
 1964,
 0,
 1946,
 1955,
 0,
 0,
 0,
 2159,
 0,
 0,
 1953,
 0,
 0,
 1941,
 0,
 2313,
 0,
 2003,
 2101,
 0,
 0,
 0,
 2423,
 0,
 0,
 1960,
 0,
 2199,
 0,
 0,
 2115,
 0,
 0,
 0,
 0,
 2030,
 1947,
 0,
 2057,
 0,
 0,
 0,
 1958,
 0,
 2023,
 2033,
 1997,
 0,
 1994,
 0,
 2026,
 0,
 0,
 2619,
 0,
 2414,
 0,
 2046,
 2245,
 2382,
 0,
 0,
 0,
 0,
 1923,
 0,
 0,
 0,
 0,
 0,
 1932,
 0,
 0,
 0,
 0,
 1938,
 0,
 0,
 0,
 0,
 2355,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1921,
 1952,
 0,
 0,
 0,
 2210,
 0,
 2027,
 0,
 2083,
 0,
 0,
 1956,
 0,
 2183,
 0,
 0,
 2129,
 0,
 1934,
 2379,
 0,
 2247,
 0,
 0,
 0,
 0,
 0,
 1946,
 0,
 0,
 0,
 2044,
 0,
 0,
 0,
 1997,
 0,
 0,
 0,
 1943,
 0,
 0,
 0,
 0,
 2003,
 2223,
 0,
 1941,
 0,
 1933,
 2050,
 2130,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2238,
 0,
 2016,
 1963,
 0,
 1949,
 0,
 0,
 0,
 2054,
 0,
 0,
 0,
 0,
 2205,
 0,
 0,
 0,
 0,
 0,
 1951,
 0,
 0,
 2200,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2142,
 1986,
 1975,
 0,
 0,
 0,
 0,
 1932,
 0,
 0,
 1937,
 2162,
 0,
 0,
 0,
 2013,
 0,
 2064,
 0,
 2439,
 2017,
 0,
 0,
 0,
 0,
 1953,
 0,
 0,
 0,
 2038,
 2794,
 2088,
 0,
 0,
 2306,
 2188,
 0,
 2080,
 0,
 2039,
 0,
 2032,
 0,
 0,
 0,
 2091,
 0,
 0,
 0,
 0,
 0,
 2428,
 0,
 0,
 0,
 2490,
 2058,
 1974,
 0,
 2107,
 0,
 2013,
 0,
 1941,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2081,
 1936,
 2091,
 0,
 0,
 0,
 0,
 0,
 1948,
 0,
 0,
 0,
 0,
 1943,
 0,
 0,
 0,
 2047,
 0,
 0,
 1978,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1971,
 0,
 0,
 2111,
 0,
 0,
 0,
 1938,
 2213,
 0,
 2005,
 0,
 0,
 0,
 2024,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2083,
 0,
 0,
 2076,
 0,
 0,
 2178,
 0,
 2031,
 0,
 0,
 0,
 0,
 2005,
 0,
 0,
 0,
 0,
 1992,
 0,
 2077,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2024,
 0,
 1936,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1969,
 0,
 1988,
 0,
 0,
 0,
 0,
 1945,
 2006,
 0,
 0,
 2027,
 0,
 0,
 2214,
 2002,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1944,
 2756,
 2057,
 0,
 0,
 0,
 2666,
 1961,
 2318,
 2343,
 2155,
 0,
 0,
 2095,
 0,
 0,
 0,
 0,
 1942,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2008,
 2275,
 0,
 2029,
 0,
 0,
 2215,
 2088,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1961,
 2756,
 0,
 2040,
 2380,
 1970,
 0,
 0,
 0,
 0,
 1981,
 0,
 0,
 2005,
 0,
 0,
 2101,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1995,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2185,
 0,
 0,
 0,
 0,
 0,
 2600,
 0,
 0,
 0,
 0,
 0,
 1990,
 1951,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2122,
 0,
 0,
 0,
 0,
 0,
 0,
 1958,
 0,
 1965,
 2112,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2002,
 0,
 1925,
 0,
 0,
 0,
 2044,
 0,
 2084,
 2092,
 1955,
 0,
 1945,
 0,
 0,
 2044,
 0,
 0,
 0,
 0,
 1922,
 1985,
 0,
 0,
 1934,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2196,
 0,
 0,
 2091,
 0,
 0,
 0,
 0,
 0,
 2142,
 0,
 0,
 0,
 0,
 0,
 0,
 2385,
 1924,
 0,
 0,
 0,
 0,
 2065,
 0,
 0,
 0,
 1972,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1996,
 0,
 2085,
 0,
 2016,
 2072,
 0,
 0,
 0,
 0,
 0,
 0,
 2131,
 1977,
 0,
 0,
 2035,
 0,
 2322,
 0,
 0,
 1957,
 1999,
 1999,
 2046,
 0,
 0,
 0,
 0,
 0,
 0,
 1926,
 2032,
 2068,
 0,
 2063,
 0,
 2096,
 2072,
 2210,
 2071,
 0,
 2094,
 0,
 0,
 0,
 0,
 0,
 2108,
 2098,
 0,
 0,
 0,
 0,
 2138,
 0,
 0,
 2015,
 0,
 2292,
 2083,
 0,
 0,
 0,
 2665,
 0,
 0,
 0,
 1932,
 2116,
 0,
 0,
 0,
 0,
 0,
 2355,
 0,
 0,
 2012,
 2065,
 0,
 0,
 0,
 0,
 0,
 0,
 2749,
 0,
 0,
 0,
 0,
 2055,
 0,
 0,
 0,
 0,
 0,
 1923,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2008,
 2079,
 0,
 0,
 0,
 0,
 0,
 2154,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2429,
 0,
 0,
 0,
 2030,
 2258,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [22]:
import pandas as pd

fieldnames = ['imgname', 'center', 'scale', 'res', 'rot', 'ul', 'br', 'pad', 'old_x', 'old_y', 'new_x', 'new_y']

df = pd.read_csv('notebooks/errors_v1.csv', header=None, names=fieldnames)

In [37]:
columns_to_convert = ['old_x', 'old_y', 'new_x', 'new_y']

new_df = pd.DataFrame()

for column_name in columns_to_convert:
    print(column_name)
    column_tuple = [literal_eval(row) for row in df[column_name]]
    lb_column = [x[0] for x in column_tuple]
    ub_column = [x[1] for x in column_tuple]
    new_df[str(column_name) + '_lb'] = lb_column
    new_df[str(column_name) + '_ub'] = ub_column

old_x
old_y
new_x
new_y

In [39]:
new_df.describe()

,old_x_lb,old_x_ub,old_y_lb,old_y_ub,new_x_lb,new_x_ub,new_y_lb,new_y_ub
count,5885.000000,5885.000000,5885.000000,5885.000000,5885.000000,5885.000000,5885.000000,5885.000000
mean,576.797111,317.652167,308.800170,1014.696347,874.790484,615.645540,0.216143,706.112319
std,935.794041,1024.011533,124.246911,99.721571,694.693820,563.727726,3.788760,152.462569
min,0.000000,-1912.000000,0.000000,596.000000,0.000000,-941.000000,0.000000,341.000000
25%,0.000000,-320.000000,235.000000,961.000000,0.000000,-19.000000,0.000000,594.000000
50%,0.000000,-118.000000,311.000000,1080.000000,929.000000,713.000000,0.000000,703.000000
75%,1939.000000,1920.000000,383.000000,1080.000000,1301.000000,996.000000,0.000000,806.000000
max,2861.000000,1920.000000,705.000000,1080.000000,3891.000000,2485.000000,93.000000,1173.000000

In [34]:
literal_eval(df.old_x[0])

(0, -27)

In [36]:
df.old_x[0]

'(0, -27)'

In [44]:
def break_tuples(column):
    column_tuple = [literal_eval(row) for row in column]
    lb_column = [x[0] for x in column_tuple]
    ub_column = [x[1] for x in column_tuple]
    return lb_column, ub_column

In [45]:
columns_to_convert = ['old_x', 'old_y', 'new_x', 'new_y']

new_df = pd.DataFrame()

for name in columns_to_convert:
    new_df[str(name) + '_lb'], new_df[str(name) + '_ub'] = break_tuples(df[name])

In [46]:
new_df

,old_x_lb,old_x_ub,old_y_lb,old_y_ub,new_x_lb,new_x_ub,new_y_lb,new_y_ub
0,0,-27,218,899,708,681,0,681
1,0,-571,495,1080,1345,774,0,585
2,0,-42,389,1080,1340,1298,0,691
3,0,-12,311,850,551,539,0,539
4,0,-70,18,1080,1358,1288,0,1062
5,0,-819,437,1080,1572,753,0,643
6,0,-29,334,828,523,494,0,494
7,1957,1920,292,1080,0,-37,0,788
8,0,-156,204,1080,1043,887,0,876
9,0,-234,428,1080,972,738,0,652
10,1969,1920,307,803,0,-49,0,496
11,0,-405,367,1080,1461,1056,0,713
12,2343,1920,0,1080,0,-423,12,1092
13,0,-299,337,1031,993,694,0,694
14,0,-207,173,937,971,764,0,764
15,0,-54,29,1080,1505,1451,0,1051
16,1988,1920,198,945,0,-68,0,747
17,1968,1920,270,924,0,-48,0,654
18,0,-357,214,1080,1385,1028,0,866
19,0,-216,85,1080,1433,1217,0,995
20,0,-238,391,940,788,550,0,549
21,0,-27,277,1044,794,767,0,767
22,0,-303,416,1080,1063,760,0,664
23,2153,1920,341,786,0,-233,0,445
24,0,-187,353,988,823,636,0,635
25,2109,1920,417,1080,0,-189,0,663
26,2002,1920,356,903,0,-82,0,547
27,0,-144,420,1017,741,597,0,597
28,0,-718,360,1080,1773,1055,0,720
29,2077,1920,290,1031,0,-157,0,741
...,...,...,...,...,...,...,...,...
5855,0,-359,276,1073,1156,797,0,797
5856,0,-198,323,1080,1117,919,0,757
5857,0,-142,236,825,731,589,0,589
5858,0,-20,328,826,518,498,0,498
5859,2204,1920,318,1080,0,-284,0,762
5860,0,-43,306,784,521,478,0,478
5861,0,-211,196,1080,1183,972,0,884
5862,0,-166,312,1080,1387,1221,0,768
5863,0,-82,249,1049,882,800,0,800
5864,0,-137,318,781,600,463,0,463
5865,2054,1920,429,1005,0,-134,0,576
5866,0,-491,241,1080,2083,1592,0,839
5867,1958,1920,258,1080,0,-38,0,822
5868,1938,1920,376,841,0,-18,0,465
5869,0,-664,391,1080,1492,828,0,689
5870,0,-93,341,1080,1780,1687,0,739
5871,2062,1920,231,896,0,-142,0,665
5872,0,-175,645,1080,1108,933,0,435
5873,0,-34,363,810,481,447,0,447
5874,0,-544,124,1080,2166,1622,0,956
5875,0,-234,284,796,746,512,0,512
5876,1944,1920,363,909,0,-24,0,546
5877,2368,1920,496,1080,0,-448,0,584
5878,0,-191,378,963,777,586,0,585
5879,1969,1920,146,931,0,-49,0,785
5880,0,-26,237,994,782,756,0,757
5881,1921,1920,103,961,0,-1,0,858
5882,0,-369,232,1080,1486,1117,0,848
5883,0,-568,273,948,1244,676,0,675
5884,2181,1920,237,1080,0,-261,0,843